repos:
- repo: local
  hooks:
  - id: forbid-root-artifacts
    name: Forbid root artifacts
    entry: python tools/forbid-root-artifacts/check.py
    language: python
    pass_filenames: false
    always_run: true
    additional_dependencies:
    - pyyaml
